const distritos = [
  { id: 1, distrito: "Cercado de Lima" },
  { id: 2, distrito: "Ancón" },
  { id: 3, distrito: "Ate" },
  { id: 4, distrito: "Barranco" },
  { id: 5, distrito: "Breña" },
  { id: 6, distrito: "Carabayllo" },
  { id: 7, distrito: "Comas" },
  { id: 8, distrito: "Chaclacayo" },
  { id: 9, distrito: "Chorrillos" },
  { id: 10, distrito: "El Agustino" },
  { id: 11, distrito: "Jesús María" },
  { id: 12, distrito: "La Molina" },
  { id: 13, distrito: "La Victoria" },
  { id: 14, distrito: "Lince" },
  { id: 15, distrito: "Lurigancho" },
  { id: 16, distrito: "Lurín" },
  { id: 17, distrito: "Magdalena del Mar" },
  { id: 18, distrito: "Miraflores" },
  { id: 19, distrito: "Pachacamac" },
  { id: 20, distrito: "Pucusana" },
  { id: 21, distrito: "Pueblo Libre" },
  { id: 22, distrito: "Puente Piedra" },
  { id: 23, distrito: "Punta Negra" },
  { id: 24, distrito: "Punta Hermosa" },
  { id: 25, distrito: "Rímac" },
  { id: 26, distrito: "San Bartolo" },
  { id: 27, distrito: "San Isidro" },
  { id: 28, distrito: "Independencia" },
  { id: 29, distrito: "San Juan de Miraflores" },
  { id: 30, distrito: "San Luis" },
  { id: 31, distrito: "San Martín de Porres" },
  { id: 32, distrito: "San Miguel" },
  { id: 33, distrito: "Santiago de Surco" },
  { id: 34, distrito: "Surquillo" },
  { id: 35, distrito: "Villa María del Triunfo" },
  { id: 36, distrito: "San Juan de Lurigancho" },
  { id: 37, distrito: "Santa María del Mar" },
  { id: 38, distrito: "Santa Rosa" },
  { id: 39, distrito: "Los Olivos" },
  { id: 40, distrito: "Cieneguilla" },
  { id: 41, distrito: "San Borja" },
  { id: 42, distrito: "Villa El Salvador" },
  { id: 43, distrito: "Santa Anita" },
  { id: 44, distrito: "Callao" },
  { id: 45, distrito: "Bellavista" },
  { id: 46, distrito: "Carmen de La Legua" },
  { id: 47, distrito: "La Perla" },
  { id: 48, distrito: "La Punta" },
  { id: 49, distrito: "Ventanilla" },
];

module.exports = distritos;
