const pedidos = [
  {
    id: 1,
    fecha: "15/04/2016",
    contactoRemitente: "ROBERTO LA TORRE",
    empresaRemitente: "SAGA FALABELLA S A - SAN ISIDRO",
    direccionRemitente: "AV. PASEO DE LA REPUBLICA 3220",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CLIENTE",
    empresaConsignado: "",
    direccionConsignado: "AV. PASEO DE LA REPÚBLICA 3195 OF. 301",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 10,
    tarifaSugerida: 5,
    recaudo: 0,
    tramite: 0,
    comision: 0,
    tipoCarga: "Documento/Sobre",
    formaPago: "Crédito 7 Días",
    distancia: 0,
    CO2Ahorrado: 0,
    ruido: 0,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "avallejo",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 2,
    fecha: "15/04/2016",
    contactoRemitente: "ROBERTO LA TORRE",
    empresaRemitente: "SAGA FALABELLA S A - SAN ISIDRO",
    direccionRemitente: "AV. PASEO DE LA REPUBLICA 3220",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CLIENTE",
    empresaConsignado: "",
    direccionConsignado: "AV. LA PAZ 374 - PISO 3 CDTO C",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 15,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "Crédito 7 Días",
    distancia: 7.7,
    CO2Ahorrado: 2.3,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN MIGUEL",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 3,
    fecha: "15/04/2016",
    contactoRemitente: "ROBERTO LA TORRE",
    empresaRemitente: "SAGA FALABELLA S A - SAN ISIDRO",
    direccionRemitente: "AV. PASEO DE LA REPUBLICA 3220",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CLIENTE",
    empresaConsignado: "",
    direccionConsignado: "CALLE SAN RODOLFO MZ P LT 1C URB. VILLA MARINA",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 20,
    tarifaSugerida: 21,
    recaudo: 0,
    tramite: 0,
    comision: 14,
    tipoCarga: "Documento/Sobre",
    formaPago: "Crédito 7 Días",
    distancia: 11.8,
    CO2Ahorrado: 3.5,
    ruido: 0.3,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "CHORRILLOS",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 4,
    fecha: "15/04/2016",
    contactoRemitente: "ROBERTO LA TORRE",
    empresaRemitente: "SAGA FALABELLA S A - SAN ISIDRO",
    direccionRemitente: "AV. PASEO DE LA REPUBLICA 3220",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CLIENTE",
    empresaConsignado: "",
    direccionConsignado: "CALLE NUEVA ESPARTA 124 DPTO 101 URB. LOS CEDROS",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 20,
    tarifaSugerida: 23,
    recaudo: 0,
    tramite: 0,
    comision: 14,
    tipoCarga: "Documento/Sobre",
    formaPago: "Crédito 7 Días",
    distancia: 13.3,
    CO2Ahorrado: 4,
    ruido: 0.3,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "CHORRILLOS",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 5,
    fecha: "15/04/2016",
    contactoRemitente: "ROBERTO LA TORRE",
    empresaRemitente: "SAGA FALABELLA S A - SAN ISIDRO",
    direccionRemitente: "AV. PASEO DE LA REPUBLICA 3220",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CLIENTE",
    empresaConsignado: "",
    direccionConsignado: "URB. LA CRUCETA III BLOCK 5 DPTO 201",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 16,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "Crédito 7 Días",
    distancia: 8.5,
    CO2Ahorrado: 2.6,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "Santiago de Surco",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 6,
    fecha: "15/04/2016",
    contactoRemitente: "GLORIA ARELLANO",
    empresaRemitente: "CENTRO INTERNACIONAL DE LA PAPA",
    direccionRemitente: "AV. LA MOLINA 1895",
    distritoRemitente: "La Molina",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "MESA DE PARTES",
    empresaConsignado: "MINISTERIO DE AGRICULTURA - MINAGRI",
    direccionConsignado: "JR. YAUYOS 258",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 25,
    tarifaSugerida: 20,
    recaudo: 0,
    tramite: 0,
    comision: 17.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 10.9,
    CO2Ahorrado: 3.3,
    ruido: 0.3,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "CERCADO DE LIMA",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 7,
    fecha: "11/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "ADMINISTRADOR",
    empresaConsignado: "QUINOA DEAN VALDIVIA",
    direccionConsignado: "DEAN VALDIVIA 135",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 10,
    tarifaSugerida: 14,
    recaudo: 0,
    tramite: 0,
    comision: 7,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 6.4,
    CO2Ahorrado: 1.9,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 8,
    fecha: "16/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "CARLOS LAZO",
    empresaConsignado: "",
    direccionConsignado: "C.C. LA RAMBLA",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "FERIA AGROPERCUARIA",
    tarifa: 16,
    tarifaSugerida: 14,
    recaudo: 0,
    tramite: 0,
    comision: 11.2,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 7,
    CO2Ahorrado: 2.1,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "San Borja",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 9,
    fecha: "18/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "6 KEKES",
    contactoConsignado: "ADMNISTRADORA",
    empresaConsignado: "QUINOA PARDO Y ALIAGA",
    direccionConsignado: "AV. PARDO Y ALIAGA 664",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 10,
    tarifaSugerida: 12,
    recaudo: 0,
    tramite: 0,
    comision: 7,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 5.6,
    CO2Ahorrado: 1.7,
    ruido: 0.1,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 10,
    fecha: "15/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "2 KEKES",
    contactoConsignado: "ADMNISTRADORA",
    empresaConsignado: "QUINOA PARDO Y ALIAGA",
    direccionConsignado: "AV. PARDO Y ALIAGA 664",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 10,
    tarifaSugerida: 12,
    recaudo: 0,
    tramite: 0,
    comision: 7,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 5.6,
    CO2Ahorrado: 1.7,
    ruido: 0.1,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 11,
    fecha: "18/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "10 KEKES",
    contactoConsignado: "ADMNISTRADORA",
    empresaConsignado: "QUINOA CAMINO REAL",
    direccionConsignado: "VÍA REAL S/N - CENTRO EMPRESARIAL CAMINO REAL",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "INGRESAR POR CHOQUEHUANCA",
    tarifa: 10,
    tarifaSugerida: 7,
    recaudo: 0,
    tramite: 0,
    comision: 7,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 1.5,
    CO2Ahorrado: 0.4,
    ruido: 0,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 12,
    fecha: "18/04/2016",
    contactoRemitente: "MARITI",
    empresaRemitente: "LA PANA E.I.R.L.",
    direccionRemitente: "JR. ALFONSO UGARTE 141",
    distritoRemitente: "Barranco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "10 KEKES",
    contactoConsignado: "ADMINISTRADOR",
    empresaConsignado: "QUINOA DEAN VALDIVIA",
    direccionConsignado: "DEAN VALDIVIA 135",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 10,
    tarifaSugerida: 14,
    recaudo: 0,
    tramite: 0,
    comision: 7,
    tipoCarga: "Producto Alimenticio",
    formaPago: "Crédito 7 Días",
    distancia: 6.4,
    CO2Ahorrado: 1.9,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "E-COMMERCE",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 13,
    fecha: "18/04/2016",
    contactoRemitente: "CARMEN NAPAICO",
    empresaRemitente: "NAPAICO MEZA CARMEN ISABEL",
    direccionRemitente: "CALLE 6 185",
    distritoRemitente: "Santiago de Surco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "EDIFICIO E8 DPTO 802 - PARQUE DE SURCO III",
    contactoConsignado: "GLADYS NÚÑEZ",
    empresaConsignado: "",
    direccionConsignado: "CONDOMINIO DEL AIRE BLOCK G2 DPTO 503",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "CRUCE DE AV. SAN LUIS Y AV. DEL AIRE",
    tarifa: 15,
    tarifaSugerida: 26,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 15.5,
    CO2Ahorrado: 4.7,
    ruido: 0.4,
    rolCliente: "DESTINATARIO",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN LUIS",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 14,
    fecha: "14/04/2016",
    contactoRemitente: "LUCIA VASQUEZ",
    empresaRemitente: "TERAPIA DE ARTES EXPRESIVAS PERU",
    direccionRemitente: "CALLE AYACUCHO 166",
    distritoRemitente: "Miraflores",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "JOSÉ MIGUEL CALDERÓN",
    empresaConsignado: "",
    direccionConsignado: "CALLE LAS PALMERAS 331 - DPTO 602",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 8,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 2.5,
    CO2Ahorrado: 0.7,
    ruido: 0.1,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN ISIDRO",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 15,
    fecha: "19/04/2016",
    contactoRemitente: "LUCIA VASQUEZ",
    empresaRemitente: "TERAPIA DE ARTES EXPRESIVAS PERU",
    direccionRemitente: "CALLE AYACUCHO 166",
    distritoRemitente: "Miraflores",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "ROSA GARIBALDI",
    empresaConsignado: "",
    direccionConsignado: "MONTE CARMELO 330",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "PRIMER ENVÍO",
    tarifa: 15,
    tarifaSugerida: 13,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 5.7,
    CO2Ahorrado: 1.7,
    ruido: 0.1,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "Santiago de Surco",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 16,
    fecha: "19/04/2016",
    contactoRemitente: "LUCIA VASQUEZ",
    empresaRemitente: "TERAPIA DE ARTES EXPRESIVAS PERU",
    direccionRemitente: "CALLE AYACUCHO 166",
    distritoRemitente: "Miraflores",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "ROSA GARIBALDI",
    empresaConsignado: "",
    direccionConsignado: "MONTE CARMELO 330",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "SEGUNDO ENVÍO",
    tarifa: 15,
    tarifaSugerida: 13,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 5.7,
    CO2Ahorrado: 1.7,
    ruido: 0.1,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "Santiago de Surco",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 17,
    fecha: "20/04/2016",
    contactoRemitente: "LUCIA VASQUEZ",
    empresaRemitente: "TERAPIA DE ARTES EXPRESIVAS PERU",
    direccionRemitente: "CALLE AYACUCHO 166",
    distritoRemitente: "Miraflores",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "MESA DE PARTES",
    empresaConsignado: "MINISTERIO DE EDUCACIÓN - MINEDU",
    direccionConsignado: "EL COMERCIO 193",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 22.5,
    tarifaSugerida: 18,
    recaudo: 0,
    tramite: 7.5,
    comision: 15.75,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 10.4,
    CO2Ahorrado: 6.2,
    ruido: 0.3,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "San Borja",
    modalidad: "CON RETORNO",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 2,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 18,
    fecha: "20/04/2016",
    contactoRemitente: "PAMELA DIAZ",
    empresaRemitente:
      "ORGANIZACION INTERNACIONAL DE MUJERES EN NEGOCIOS DEL PERU - OWIT",
    direccionRemitente: "LOS LAURELES 365",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "MESA DE PARTES",
    empresaConsignado: "FERREYROS",
    direccionConsignado: "CRISTÓBAL DE PERALTA NORTE 820",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 13.5,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 6.1,
    CO2Ahorrado: 3.7,
    ruido: 0.2,
    rolCliente: "REMITENTE",
    comentario: "Migración del Sistema",
    distritoConsignado: "Santiago de Surco",
    modalidad: "CON RETORNO",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 2,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 19,
    fecha: "20/04/2016",
    contactoRemitente: "PAMELA DIAZ",
    empresaRemitente:
      "ORGANIZACION INTERNACIONAL DE MUJERES EN NEGOCIOS DEL PERU - OWIT",
    direccionRemitente: "LOS LAURELES 365",
    distritoRemitente: "San Isidro",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "",
    contactoConsignado: "MESA DE PARTES",
    empresaConsignado: "FERREYROS",
    direccionConsignado: "CRISTÓBAL DE PERALTA NORTE 820",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 9,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "Efectivo en Destino",
    distancia: 3,
    CO2Ahorrado: 0.9,
    ruido: 0.1,
    rolCliente: "DESTINATARIO",
    comentario: "Migración del Sistema",
    distritoConsignado: "Santiago de Surco",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "ALDO LONDOÑE",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
  {
    id: 20,
    fecha: "20/04/2016",
    contactoRemitente: "CARMEN NAPAICO",
    empresaRemitente: "NAPAICO MEZA CARMEN ISABEL",
    direccionRemitente: "CALLE 6 185",
    distritoRemitente: "Santiago de Surco",
    telefonoRemitente: "Sin teléfono",
    otroDatoRemitente: "EDIFICIO E8 DPTO 802 - PARQUE DE SURCO III",
    contactoConsignado: "GLADYS NUÑEZ",
    empresaConsignado: "",
    direccionConsignado: "CONDOMINIO DEL AIRE BLOCK G2 DPTO 503",
    telefonoConsignado: "Sin teléfono",
    otroDatoConsignado: "",
    tarifa: 15,
    tarifaSugerida: 26,
    recaudo: 0,
    tramite: 0,
    comision: 10.5,
    tipoCarga: "Documento/Sobre",
    formaPago: "EFECTIVO EN ORIGEN",
    distancia: 15.5,
    CO2Ahorrado: 4.7,
    ruido: 0.4,
    rolCliente: "DESTINATARIO",
    comentario: "Migración del Sistema",
    distritoConsignado: "SAN LUIS",
    modalidad: "UNA VÍA",
    tipoDeEnvio: "EXPRESS",
    status: 4,
    mobiker: "FERNANDO CARBAJAL",
    operador: "FCARBAJAL",
    viajes: 1,
    facturado: "SI",
    compensado: "SI",
  },
];

module.exports = pedidos;
