const mobikers = [
  {
    nombres: "Abraham",
    apellidos: "Agüero",
    fullName: "Abraham Agüero",
    telefono: 963761900,
    telegram: "Mob1",
    direccion: "Street1",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker1@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-12 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 32,
  },
  {
    nombres: "Alberto",
    apellidos: "Hernandez",
    fullName: "Alberto Hernandez",
    telefono: 931089194,
    telegram: "tioMoB",
    direccion: "Batallón Angamos",
    tipoDocumento: "DNI",
    numeroDocumento: 11111111,
    email: "mob@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1981-04-12 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 33,
  },
  {
    nombres: "Alejandro",
    apellidos: "Medina",
    fullName: "Alejandro Medina",
    telefono: 959217060,
    telegram: "Mob3",
    direccion: "Street3",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker3@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-14 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 43,
  },
  {
    nombres: "Anderson Alexander",
    apellidos: "Vallejo",
    fullName: "Anderson Vallejo",
    telefono: 977320576,
    telegram: "vallejoanderson",
    direccion: "Calle Francisco de Zela",
    tipoDocumento: "Carnet de Extranjería",
    numeroDocumento: 2766257,
    email: "vallejoanderson@gmail.com",
    genero: "Masculino",
    banco: "Banco de Crédito del Perú (BCP)",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "1991-05-19 20:47:00",
    fechaIngreso: "2018-09-01 20:47:00",
    distrito: 9,
  },
  {
    nombres: "Angel",
    apellidos: "Guzman Morales",
    fullName: "Angel Guzman",
    telefono: 961789498,
    telegram: "Aguzman",
    direccion: "Calle independencia 509",
    tipoDocumento: "DNI",
    numeroDocumento: 45666403,
    email: "obebmusic1@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1989-03-26 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 32,
  },
  {
    nombres: "Angel",
    apellidos: "Villacruz",
    fullName: "Angel Villacruz",
    telefono: 912998807,
    telegram: "Mob6",
    direccion: "Street6",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker6@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-17 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 34,
  },
  {
    nombres: "Angelica",
    apellidos: "Moreno",
    fullName: "Angelica Moreno",
    telefono: 910861201,
    telegram: "Mob7",
    direccion: "Street7",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker7@mob.com",
    genero: "Femenino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-18 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Armando",
    apellidos: "Kingan",
    fullName: "Armando Kingan",
    telefono: 998361892,
    telegram: "Mob8",
    direccion: "Street8",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker8@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-19 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Carlos",
    apellidos: "Abdala",
    fullName: "Carlos Abdala",
    telefono: 927947696,
    telegram: "Mob9",
    direccion: "Street9",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker9@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-20 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Ciceron",
    apellidos: "Cabanillas",
    fullName: "Ciceron Cabanillas",
    telefono: 984338963,
    telegram: "Mob10",
    direccion: "Street10",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker10@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-21 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Cristian",
    apellidos: "Tueros",
    fullName: "Cristian Tueros",
    telefono: 933629229,
    telegram: "Mob11",
    direccion: "Street11",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker11@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-22 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 12,
  },
  {
    nombres: "Daniel Alejandro",
    apellidos: "Colmenares Duque",
    fullName: "Daniel Colmenares",
    telefono: 910604446,
    telegram: "Hardrack",
    direccion: "Calle Narciso de la Colina 771",
    tipoDocumento: "Carnet de Extranjería",
    numeroDocumento: 11111111,
    email: "dan@dan.com",
    genero: "No Binario",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1993-01-06 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 34,
  },
  {
    nombres: "Danny",
    apellidos: "Salazar",
    fullName: "Danny Salazar",
    telefono: 995727703,
    telegram: "Mob13",
    direccion: "Street13",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker13@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-24 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 21,
  },
  {
    nombres: "David",
    apellidos: "Balvin Soto",
    fullName: "David Balvin",
    telefono: 932117309,
    telegram: "mr",
    direccion: "Calle bucaramanga mz x1 lt 2",
    tipoDocumento: "DNI",
    numeroDocumento: 41851678,
    email: "dbalvin32@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1983-03-23 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 12,
  },
  {
    nombres: "Diego",
    apellidos: "Satori",
    fullName: "Diego Satori",
    telefono: 981174210,
    telegram: "Mob15",
    direccion: "Street15",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker15@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-26 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 44,
  },
  {
    nombres: "Diober",
    apellidos: "Carreño",
    fullName: "Diober Carreño",
    telefono: 931686125,
    telegram: "Mob16",
    direccion: "Street16",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker16@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-27 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 39,
  },
  {
    nombres: "Eduardo",
    apellidos: "Carbajal",
    fullName: "Eduardo Carbajal",
    telefono: 922338449,
    telegram: "Mob17",
    direccion: "Street17",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker17@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-28 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 36,
  },
  {
    nombres: "Edinson",
    apellidos: "Salcedo Santiago",
    fullName: "Edinson Salcedo",
    telefono: 933285053,
    telegram: "ed",
    direccion: "Los jazmines manzana R lote 38",
    tipoDocumento: "DNI",
    numeroDocumento: 45471101,
    email: "edinsonsalcedosan@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Jaba/Canastilla",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1988-10-03 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 44,
  },
  {
    nombres: "Edwin",
    apellidos: "Arnedo",
    fullName: "Edwin Arnedo",
    telefono: 924617851,
    telegram: "Mob18",
    direccion: "Street18",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker18@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-29 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 32,
  },
  {
    nombres: "Elias",
    apellidos: "Ortiz",
    fullName: "Elias Ortiz",
    telefono: 923547106,
    telegram: "Mob19",
    direccion: "Street19",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker19@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-04-30 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 44,
  },
  {
    nombres: "Erinso",
    apellidos: "Moreno",
    fullName: "Erinso Moreno",
    telefono: 928188911,
    telegram: "Mob20",
    direccion: "Street20",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker20@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-01 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 4,
  },
  {
    nombres: "Fabrizio Rodolfo",
    apellidos: "Yabar Perez",
    fullName: "Fabrizio Yabar",
    telefono: 968688877,
    telegram: "fabrizio",
    direccion: "Jr. Galileo Galilei 264 Piso 2",
    tipoDocumento: "DNI",
    numeroDocumento: 45471101,
    email: "fabrizioyabper91@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Caja Térmica",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "1991-01-10 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 33,
  },
  {
    nombres: "Fernando José",
    apellidos: "Carbajal Luy",
    fullName: "Fernando Carbajal",
    telefono: 997253964,
    telegram: "fcarbajal",
    direccion: "Calle Loma Umbrosa 853",
    tipoDocumento: "DNI",
    numeroDocumento: 11111111,
    email: "mob@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "Rutera/Fixie",
    status: "Activo",
    fechaNacimiento: "1983-04-12 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 33,
  },
  {
    nombres: "Gaby",
    apellidos: "Viloria",
    fullName: "Gaby Viloria",
    telefono: 913489130,
    telegram: "Mob22",
    direccion: "Street22",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker22@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-03 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Greg",
    apellidos: "Durand",
    fullName: "Greg Durand",
    telefono: 902075306,
    telegram: "Mob23",
    direccion: "Street23",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker23@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-04 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 1,
  },
  {
    nombres: "Henry",
    apellidos: "Romero",
    fullName: "Henry Romero",
    telefono: 981154940,
    telegram: "Mob24",
    direccion: "Street24",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker24@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-05 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 9,
  },
  {
    nombres: "Hugo",
    apellidos: "Yañez",
    fullName: "Hugo Yañez",
    telefono: 954186992,
    telegram: "Mob25",
    direccion: "Street25",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker25@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-06 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Ilen",
    apellidos: "Moya",
    fullName: "Ilen Moya",
    telefono: 992214531,
    telegram: "Mob26",
    direccion: "Street26",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker26@mob.com",
    genero: "Femenino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-07 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 9,
  },
  {
    nombres: "Joan Manuel",
    apellidos: "Dávila",
    fullName: "Joan Manuel Dávila",
    telefono: 946994835,
    telegram: "Mob27",
    direccion: "Street27",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker27@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-08 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 17,
  },
  {
    nombres: "Jonel",
    apellidos: "Alegre",
    fullName: "Jonel Alegre",
    telefono: 955549606,
    telegram: "Mob28",
    direccion: "Street28",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker28@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-09 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 36,
  },
  {
    nombres: "Jorge Luis",
    apellidos: "Dorantes",
    fullName: "Jorge Luis Dorantes",
    telefono: 966122031,
    telegram: "Mob29",
    direccion: "Street29",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker29@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-10 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 39,
  },
  {
    nombres: "Jorge Luis",
    apellidos: "Sanchez",
    fullName: "Jorge Luis Sanchez",
    telefono: 960796972,
    telegram: "Mob30",
    direccion: "Street30",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker30@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-11 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 36,
  },
  {
    nombres: "Jorge",
    apellidos: "Showing",
    fullName: "Jorge Showing",
    telefono: 999999999,
    telegram: "Mob31",
    direccion: "Street31",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker31@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-12 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Jose",
    apellidos: "Castro",
    fullName: "Jose Castro",
    telefono: 956339251,
    telegram: "Mob32",
    direccion: "Street32",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker32@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-13 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 11,
  },
  {
    nombres: "Jose",
    apellidos: "Garcia Alvarado",
    fullName: "Jose Garcia Alvarado",
    telefono: 923794036,
    telegram: "Mob33",
    direccion: "Street33",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker33@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-14 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 31,
  },
  {
    nombres: "Jose",
    apellidos: "Julca",
    fullName: "Jose Julca",
    telefono: 940171200,
    telegram: "Mob34",
    direccion: "Street34",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker34@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-15 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 4,
  },
  {
    nombres: "Jose Martin",
    apellidos: "Soria Pacheco",
    fullName: "José Soria",
    telefono: 928224373,
    telegram: "jsoria",
    direccion: "Av. El Sol Mz Y Lote 13 C Urb. La Campiña - Chorrillos",
    tipoDocumento: "DNI",
    numeroDocumento: 74629962,
    email: "josemartin176@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Jaba/Canastilla",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "1994-12-07 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 9,
  },
  {
    nombres: "Juan",
    apellidos: "Alcantara",
    fullName: "Juan Alcantara",
    telefono: 956785080,
    telegram: "Mob36",
    direccion: "Street36",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker36@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-17 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Juan",
    apellidos: "Bustamante",
    fullName: "Juan Bustamante",
    telefono: 949299433,
    telegram: "Mob37",
    direccion: "Street37",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker37@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-18 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 44,
  },
  {
    nombres: "Juan Carlos",
    apellidos: "Laura",
    fullName: "Juan Carlos Laura",
    telefono: 943336314,
    telegram: "Mob38",
    direccion: "Street38",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker38@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-19 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 5,
  },
  {
    nombres: "Kevin",
    apellidos: "Farro",
    fullName: "Kevin Farro",
    telefono: 985160360,
    telegram: "Mob39",
    direccion: "Street39",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker39@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-20 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 14,
  },
  {
    nombres: "Kevin",
    apellidos: "Orilla",
    fullName: "Kevin Orilla",
    telefono: 994224691,
    telegram: "Mob40",
    direccion: "Street40",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker40@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-21 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 3,
  },
  {
    nombres: "Luis",
    apellidos: "Molina",
    fullName: "Luis Molina",
    telefono: 984104623,
    telegram: "Mob41",
    direccion: "Street41",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker41@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-22 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 34,
  },
  {
    nombres: "Luis",
    apellidos: "Pino",
    fullName: "Luis Pino",
    telefono: 997739493,
    telegram: "Mob42",
    direccion: "Street42",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker42@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-23 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 17,
  },
  {
    nombres: "Malon",
    apellidos: "Camino",
    fullName: "Malon Camino",
    telefono: 936102372,
    telegram: "Mob43",
    direccion: "Street43",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker43@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-24 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 5,
  },
  {
    nombres: "Maria Fe",
    apellidos: "Gallardo",
    fullName: "Maria Fe Gallardo",
    telefono: 902457332,
    telegram: "Mob44",
    direccion: "Street44",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker44@mob.com",
    genero: "Femenino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-25 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 11,
  },
  {
    nombres: "Mario",
    apellidos: "Zegarra",
    fullName: "Mario Zegarra",
    telefono: 969751049,
    telegram: "Mob45",
    direccion: "Street45",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker45@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-26 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 1,
  },
  {
    nombres: "Maripili",
    apellidos: "Arenas",
    fullName: "Maripili Arenas",
    telefono: 99966333,
    telegram: "Mob46",
    direccion: "Street46",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker46@mob.com",
    genero: "Femenino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-27 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 9,
  },
  {
    nombres: "Miguel",
    apellidos: "Hanke",
    fullName: "Miguel Hanke",
    telefono: 941460832,
    telegram: "Mob47",
    direccion: "Street47",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker47@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-28 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 17,
  },
  {
    nombres: "Miguel",
    apellidos: "Romero",
    fullName: "Miguel Romero",
    telefono: 980944622,
    telegram: "Mob48",
    direccion: "Street48",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker48@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-29 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 44,
  },
  {
    nombres: "Mileidy",
    apellidos: "Karina",
    fullName: "Mileidy Karina",
    telefono: 935896735,
    telegram: "Mob49",
    direccion: "Street49",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker49@mob.com",
    genero: "Femenino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-30 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 9,
  },
  {
    nombres: "Moises",
    apellidos: "Cabrera",
    fullName: "Moises Cabrera",
    telefono: 927803793,
    telegram: "Mob50",
    direccion: "Street50",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker50@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-05-31 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 12,
  },
  {
    nombres: "Pablo",
    apellidos: "Cancino",
    fullName: "Pablo Cancino",
    telefono: 972129648,
    telegram: "Mob51",
    direccion: "Street51",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker51@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-01 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 33,
  },
  {
    nombres: "Pablo",
    apellidos: "Pereda",
    fullName: "Pablo Pereda",
    telefono: 962204301,
    telegram: "Mob52",
    direccion: "Street52",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker52@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-02 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 39,
  },
  {
    nombres: "Ricardo",
    apellidos: "Astoyauri",
    fullName: "Ricardo Astoyauri",
    telefono: 994561352,
    telegram: "Mob53",
    direccion: "Street53",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker53@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-03 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 34,
  },
  {
    nombres: "Ricardo",
    apellidos: "Ruiz",
    fullName: "Ricardo Ruiz",
    telefono: 961729446,
    telegram: "Mob54",
    direccion: "Street54",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker54@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-04 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 17,
  },
  {
    nombres: "Roberto",
    apellidos: "Peña",
    fullName: "Roberto Peña",
    telefono: 996570351,
    telegram: "Mob55",
    direccion: "Street55",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker55@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-05 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 32,
  },
  {
    nombres: "Ronald",
    apellidos: "Cova",
    fullName: "Ronald Cova",
    telefono: 928439197,
    telegram: "Mob56",
    direccion: "Street56",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker56@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-06 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 9,
  },
  {
    nombres: "Ronald",
    apellidos: "Salazar",
    fullName: "Ronald Salazar",
    telefono: 919055152,
    telegram: "Mob57",
    direccion: "Street57",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker57@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-07 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 34,
  },
  {
    nombres: "Ronnie",
    apellidos: "Rodriguez",
    fullName: "Ronnie Rodriguez",
    telefono: 944940360,
    telegram: "Mob58",
    direccion: "Street58",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker58@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-08 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 4,
  },
  {
    nombres: "Ronnie bryan",
    apellidos: "Tasayco Tasayco",
    fullName: "Ronnie Tasayco",
    telefono: 900649426,
    telegram: "ronnieT",
    direccion: "La cruceta III Etapa block 09",
    tipoDocumento: "DNI",
    numeroDocumento: 74958007,
    email: "ronnie030297@gmail.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "1997-02-03 18:10:50",
    fechaIngreso: "2013-04-12 18:10:50",
    distrito: 33,
  },
  {
    nombres: "Sebastian",
    apellidos: "Prado",
    fullName: "Sebastian Prado",
    telefono: 970364292,
    telegram: "Mob60",
    direccion: "Street60",
    tipoDocumento: "DNI",
    numeroDocumento: 12345678,
    email: "biker60@mob.com",
    genero: "Masculino",
    banco: "Sin Banco",
    tipoCuenta: "Sin Cuenta",
    numeroCuentaBancaria: 0,
    equipo: "Mochila",
    tipoBicicleta: "MTB",
    status: "Activo",
    fechaNacimiento: "2013-06-10 23:10:50",
    fechaIngreso: "2013-04-12 23:10:50",
    distrito: 30,
  },
];

module.exports = mobikers;
