const clientes = [
	{
		contacto: "Patricia Guerrero",
		empresa: "Funny Market",
		direccion: "Calle Deluchi 101 B",
		telefono: 123456789,
		otroDato: "Recoger antes de las 10:30 am",
		email: "funny@market.com",
		distrito: 4,
		comprobante: 4,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 7,
	},
	{
		contacto: "Giannina Solari",
		empresa: "Café 3.0",
		direccion: "Calle Lizardo Alzamora Este 165",
		telefono: 123456789,
		otroDato: "Recoger a las 9:00 am",
		email: "cafe@cafe.com",
		distrito: 27,
		comprobante: 4,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 2,
	},
	{
		contacto: "Percy Balazar",
		empresa: "COFIDE",
		direccion: "Calle Augusto Tamayo 160",
		telefono: 123456789,
		// otroDato: "Recoger a las 9:00 am",
		email: "cofide@cofide.com",
		distrito: 27,
		comprobante: 2,
		rol: 1,
		tipoEnvio: 2,
		carga: 3,
		pago: 2,
	},
	{
		contacto: "Cristina Paz",
		empresa: "Omaha Sociedad Gestora S.A.C.",
		direccion: "Calle Aldabas 559 Oficina 501",
		telefono: 997315223,
		// otroDato: "Recoger a las 9:00 am",
		email: "cristinaPaz@omaha.com",
		distrito: 33,
		comprobante: 2,
		rol: 1,
		tipoEnvio: 2,
		carga: 3,
		pago: 2,
	},
	{
		contacto: "Javier Quijano Ono",
		empresa: "Javier Quijano Ono",
		direccion: "Avenida La Mar Oficina 401",
		telefono: 989011913,
		otroDato: "Recoger desde las 12:00 pm",
		email: "javier@javier.com",
		distrito: 32,
		comprobante: 2,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 7,
	},
	{
		contacto: "Verónica Bedoya",
		empresa: "Look Recuerditos",
		direccion: "Jr Iquique 530",
		telefono: 965805472,
		otroDato: "Recoger desde las 12:00 pm",
		email: "vero@recuerditos.com",
		distrito: 5,
		comprobante: 4,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 7,
	},
	{
		contacto: "Lili Ugarte Riva",
		empresa: "Lili Ugarte",
		direccion: "Avenida José Galvez Barrenechea 121",
		telefono: 999731522,
		otroDato: "Tocar cadena de campana o llamar al llegar",
		email: "lili@ugarte.com",
		distrito: 27,
		comprobante: 4,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 7,
	},
	{
		contacto: "Katy Aguirre",
		empresa: "Philip Morris Perú S.A.",
		direccion: "Calle Tangarara C 66 Urb. La Capullana",
		telefono: 123456789,
		otroDato: "Recoger lo más pronto posible",
		email: "katy@pmpsa.com",
		distrito: 33,
		comprobante: 2,
		rol: 1,
		tipoEnvio: 2,
		carga: 3,
		pago: 2,
	},
	{
		contacto: "Wendy Elera",
		empresa: "Wendy Elera",
		direccion: "Jirón Punta Sal 303 depa 401",
		telefono: 994458323,
		// otroDato: "Recoger antes de las 10:30 am",
		email: "wendy@elera.com",
		distrito: 33,
		comprobante: 4,
		rol: 1,
		tipoEnvio: 1,
		carga: 1,
		pago: 7,
	},
];

module.exports = clientes;
