const mobikers = [
	{
		id: "11111111-1111-1111-1111-111111111111",
		nombres: "Asignar",
		apellidos: "MoBiker",
		fullName: "Asignar MoBiker",
		telefono: 999999999,
		telegram: "asignarMoB",
		direccion: "Loma Umbrosa",
		distrito: 33,
		tipoDocumento: "DNI",
		numeroDocumento: 11111111,
		genero: "No Binario",
		email: "mob@mob.com",
		fechaNacimiento: "2013-04-12 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Daniel Alejandro",
		apellidos: "Colmenares Duque",
		fullName: "Daniel Colmenares",
		telefono: 910604446,
		telegram: "Hardrack",
		direccion: "Calle Narciso de la Colina 771",
		distrito: 34,
		tipoDocumento: "Carnet de Extranjería",
		numeroDocumento: 11111111,
		genero: "Masculino",
		email: "dan@dan.com",
		fechaNacimiento: "1993-01-06 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Alberto",
		apellidos: "Hernández",
		fullName: "Alberto Hernández",
		telefono: 999999999,
		telegram: "tioMoB",
		direccion: "Batallón Angamos",
		distrito: 33,
		tipoDocumento: "DNI",
		numeroDocumento: 11111111,
		genero: "Masculino",
		email: "mob@mob.com",
		fechaNacimiento: "1981-04-12 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Fernando José",
		apellidos: "Carbajal Luy",
		fullName: "Fernando Carbajal",
		telefono: 999999999,
		telegram: "fcarbajal",
		direccion: "Calle Loma Umbrosa 853",
		distrito: 33,
		tipoDocumento: "DNI",
		numeroDocumento: 11111111,
		genero: "Masculino",
		email: "mob@mob.com",
		fechaNacimiento: "1983-04-12 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "David",
		apellidos: "Balvin Soto",
		fullName: "David Balvin",
		telefono: 932117309,
		telegram: "mr",
		direccion: "Calle bucaramanga mz x1 lt 2",
		distrito: 12,
		tipoDocumento: "DNI",
		numeroDocumento: 41851678,
		genero: "Masculino",
		email: "dbalvin32@gmail.com",
		fechaNacimiento: "1983-03-23 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Edinson",
		apellidos: "Salcedo Santiago",
		fullName: "Edinson Salcedo",
		telefono: 933285053,
		telegram: "ed",
		direccion: "Los jazmines manzana R lote 38",
		distrito: 44,
		tipoDocumento: "DNI",
		numeroDocumento: 45471101,
		genero: "Masculino",
		email: "edinsonsalcedosan@gmail.com",
		fechaNacimiento: "1988-10-03 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Jaba/Canastilla",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Fabrizio Rodolfo",
		apellidos: "Yábar Perez",
		fullName: "Fabrizio Yábar",
		telefono: 968688877,
		telegram: "fabrizio",
		direccion: "Jr. Galileo Galilei 264 Piso 2",
		distrito: 33,
		tipoDocumento: "DNI",
		numeroDocumento: 45471101,
		genero: "Masculino",
		email: "fabrizioyabper91@gmail.com",
		fechaNacimiento: "1991-01-10 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Caja Térmica",
		tipoBicicleta: "MTB",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Ángel",
		apellidos: "Guzmán Morales",
		fullName: "Ángel Guzmán",
		telefono: 961789498,
		telegram: "Aguzman",
		direccion: "Calle independencia 509",
		distrito: 32,
		tipoDocumento: "DNI",
		numeroDocumento: 45666403,
		genero: "Masculino",
		email: "obebmusic1@gmail.com",
		fechaNacimiento: "1989-03-26 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "Rutera/Fixie",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "Ronnie bryan",
		apellidos: "Tasayco Tasayco",
		fullName: "Ronnie Tasayco",
		telefono: 900649426,
		telegram: "ronnieT",
		direccion: "La cruceta III Etapa block 09",
		distrito: 33,
		tipoDocumento: "DNI",
		numeroDocumento: 74958007,
		genero: "Masculino",
		email: "ronnie030297@gmail.com",
		fechaNacimiento: "1997-02-03 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Mochila",
		tipoBicicleta: "MTB",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
	{
		nombres: "José Martín",
		apellidos: "Soria Pacheco",
		fullName: "José Soria",
		telefono: 928224373,
		telegram: "jsoria",
		direccion: "Av. El Sol Mz Y Lote 13 C Urb. La Campiña - Chorrillos",
		distrito: 9,
		tipoDocumento: "DNI",
		numeroDocumento: 74629962,
		genero: "Masculino",
		email: "josemartin176@gmail.com",
		fechaNacimiento: "1994-12-07 18:10:50",
		banco: "Sin Banco",
		tipoCuenta: "Sin Cuenta",
		numeroCuentaBancaria: 0,
		equipo: "Jaba/Canastilla",
		tipoBicicleta: "MTB",
		fechaIngreso: "2013-04-12 18:10:50",
		status: "Activo",
	},
];

module.exports = mobikers;
